apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-nodejs
  template:
    metadata:
      labels:
        app: harness-nodejs
    spec:
      containers:
        - name: harness-nodejs
          image: prajwaltelkar14/harness-new-2.0:latest  # replaced during CD pipeline
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: harness-nodejs-service
spec:
  selector:
    app: harness-nodejs
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

